alias: Steam Deck Library
description: Save Steam Deck playtime of games into a readable JSON library.
triggers:
  - trigger: state
    entity_id: sensor.steam_deck_active_game_display
    id: game_state_change
conditions:
  - condition: template
    value_template: >
      {% set sensor = states.sensor.steam_deck_game_playtime %} {{ sensor is not
      none and sensor.state != 'unavailable' and 
      state_attr('sensor.steam_deck_game_playtime', 'games') is not none }}
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: game_state_change
          - condition: state
            entity_id: input_boolean.steam_deck_sessie_actief
            state: "off"
          - condition: template
            value_template: >
              {% set negeren = ['unknown', 'unavailable', 'none', 'idle',
              'offline', 'not playing', 'no game opened'] %} {{
              trigger.to_state.state | lower | trim not in negeren }}
        sequence:
          - action: input_datetime.set_datetime
            target:
              entity_id: input_datetime.steam_deck_sessie_starttijd
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          - action: input_text.set_value
            target:
              entity_id: input_text.steam_deck_huidige_game
            data:
              value: "{{ trigger.to_state.state | trim }}"
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.steam_deck_sessie_actief
      - conditions:
          - condition: trigger
            id: game_state_change
          - condition: state
            entity_id: input_boolean.steam_deck_sessie_actief
            state: "on"
          - condition: template
            value_template: >
              {% set negeren = ['unknown', 'unavailable', 'none', 'idle',
              'offline', 'not playing', 'no game opened'] %} {{
              trigger.to_state.state | lower | trim in negeren }}
        sequence:
          - action: shell_command.update_steam_library
            data:
              json_data: >-
                {% set current_library =
                state_attr('sensor.steam_deck_game_playtime', 'games') or {} %}

                {# 1. TIJD BEREKENING (Rekent tot het moment van nu/failsafe) #}
                {% set start_helper =
                states('input_datetime.steam_deck_sessie_starttijd') |
                as_datetime %} {% set nu_zonder_zone =
                now().replace(tzinfo=None) %} {% set duration = (nu_zonder_zone
                - start_helper).total_seconds() | float(0) %}

                {# 2. GAME NAAM TERUGHALEN (Altijd uit de text-helper voor
                reboot-veiligheid) #} {% set game_naam_opgeslagen =
                states('input_text.steam_deck_huidige_game') | trim %}

                {# Match de naam met de bestaande keys in de library
                (case-insensitive) #} {% set gevonden_naam =
                namespace(key=game_naam_opgeslagen) %} {% for bestaande_naam in
                current_library.keys() %}
                  {% if bestaande_naam | lower == game_naam_opgeslagen | lower %}
                    {% set gevonden_naam.key = bestaande_naam %}
                  {% endif %}
                {% endfor %} {% set game_naam = gevonden_naam.key %}

                {# 3. BESTAANDE DATA OPHALEN #} {% set bestaande_entry =
                current_library.get(game_naam, 0) %} {% if bestaande_entry is
                mapping %}
                  {% set oude_tijd = bestaande_entry.seconds | float(0) %}
                {% else %}
                  {% set oude_tijd = bestaande_entry | float(0) %}
                {% endif %}

                {# 4. NIEUWE JSON ENTRY SAMENSTELLEN #} {% set updated_entry = {
                  "seconds": oude_tijd + duration,
                  "last_played": start_helper.isoformat()
                } %}

                {# 5. VOLLEDIGE LIBRARY UPDATEN EN ENCODEN #} {% set
                updated_library = dict(current_library, **{game_naam:
                updated_entry}) %} {{ ({"games": updated_library} |
                to_json(pretty_print=True)) | base64_encode }}
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.steam_deck_sessie_actief
          - action: input_text.set_value
            target:
              entity_id: input_text.steam_deck_huidige_game
            data:
              value: Geen game
          - delay: "00:00:02"
          - action: homeassistant.update_entity
            target:
              entity_id: sensor.steam_deck_game_playtime
mode: single
